- name: Install unzip
  apt:
    name:
      - unzip
    update_cache: yes
    state: latest


# - name: unarchive Local file to Instance
    # src: "files/{{ file_name }}.zip"     
  # copy:  
  #   src: /index/django
  #   dest: /home/ubuntu/myproject  
    # recurse: yes
    # remote_src: yes

- name: make directory
  file:
    path: /var/www/temp
    state: directory

- name: unarchive Local file to Instance
  ansible.builtin.unarchive:
    src: "index/{{ file_name }}.zip"     
    dest: /var/www/temp

- name: move files in remote instance
  copy:
    src: /var/www/temp/
    dest: /home/ubuntu/myproject
     # force: true
    remote_src: yes

- name: remove temp folder
  file:
    path: /var/www/temp/
    state: absent

- name: Copy startup script to /myproject directory of EC2 instance
  copy:
    src: index/startup.sh
    dest: /home/ubuntu/myproject/startup.sh
    # dest: /opt/startup.sh
    mode: 0755


- name: Run startup script
  become: true
  shell: ./startup.sh &
  args:
    # chdir: /opt
    chdir: /home/ubuntu/myproject
  async: 45
  poll: 0
  







