- name: Install required list of packages
  apt:
    name: 
      - nginx
      - python3-pip
      - python3-django
    update_cache: yes
    state: latest 
  notify: 
     - restart nginx


# - name: Install required packages
#     apt:
#       name: "{{ item }}"
#       state: present
#     with_items:
#       - python3-dev
#       - python3-pip
#       - python3-virtualenv
#       - nginx

  

